server:
  port: 8080
  tomcat:
    keep-alive-timeout: 15000

spring:
  datasource:
    url: jdbc:mysql://root:wbwan2@localhost:3306/transfer?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://titan:wbwan2@localhost:3306/alcyone?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    addresses: fuji.lmq.cloudamqp.com
    username: xrhpzqhc
    password: SLHJV7wkhYMHe0CWbqsBc3cgT9jEisRX
    publisher-returns: true
    publisher-confirm-type: correlated
    virtual-host: xrhpzqhc
    listener:
      type: simple
      simple:
        acknowledge-mode: auto
        transactional: true
        prefetch: 1
        concurrency: 3
        max-concurrency: 3
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 3000
  data:
    redis:
      database: 0
      host: redis-15090.crce178.ap-east-1-1.ec2.redns.redis-cloud.com
      port: 15090
      password: TNwFAWXJUFRwDWuvCLlU32tkZqr71R5h
      timeout: 60000

logging:
  level:
    org:
      springframework:
        web: info
      hibernate: error